usuario = O QUE O USUARIO DIGITOU.
senha = O QUE O USUÁRIO DIGITOU.

SE usuario = Ederson
    SE senha = MINHA SENHA
        IR PARA PAINEL DE CONTROLE
    CASO CONTRÁRIO
        MOSTRAR QUE A SENHA ESTÁ ERRADA
CASO CONTRÁRIO
    MOSTRAR QUE ESTÁ ERRADO


email = O QUE O USUÁRIO DIGITOU

SE email = USUÁRIO DO SISTEMA
    ENVIAR EMAIL DE RECRIAÇÃO DA SENHA.
CASO CONTRÁRIO
    MOSTRAR NA TELA: Não é um usuário.